routes/dashboard.php
<?php
Route::group(['prefix'=>'cp','namespace'=>'Auth'],function(){   
    //Login Routes
    Route::get('login','LoginController@showLoginForm')->name('cpLogin');
    Route::post('login','LoginController@adminLogin')->name('adminLogin');
    Route::post('adminLogout','LoginController@adminLogout')->name('adminLogout');
    
});
Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){ 
        Route::group(['prefix' => 'cp','middleware'=>['auth:admin']], function () {
            Route::get('/','DashboardController@index')->name('cp.index');
            Route::get('/NoPermission','DashboardController@noPermission');
            //Operation route
            Route::get('operations','DashboardController@operations');
            Route::get('showOperations/{section}','DashboardController@showOperations');
            Route::get('showAdminOperations/{admin}','DashboardController@showAdminOperations');
            Route::get('delOperation/{id}','DashboardController@delOperation');
            //Settings Routes
            Route::get('settings','SettingsController@getSettings')->name('cp.getSettings');
            Route::post('settings','SettingsController@updateSettings')->name('cp.updateSettings');
            //Slider Routes
            Route::resource('sliders','SlidersController')->except('show');
            Route::get('sliders/delSlider/{id}','SlidersController@destroy');
            Route::get('sliders/archiveAll/{ids}','SlidersController@archiveAll');
            Route::get('sliders/delAll/{ids}','SlidersController@delAll');
            Route::get('sliders/changeStatus','SlidersController@changeStatus');
            Route::get('sliders_archive','SlidersController@sliders_archive');
            Route::get('sliders/restoreAll/{ids}','SlidersController@restoreAll');
            //Ads Routes
            Route::resource('ads','AdsController')->except('show');
            Route::get('ads/delAd/{id}','AdsController@destroy');
            Route::get('ads/archiveAll/{ids}','AdsController@archiveAll');
            Route::get('ads/delAll/{ids}','AdsController@delAll');
            Route::get('ads/changeStatus','AdsController@changeStatus');
            Route::get('ads_archive','AdsController@ads_archive');
            Route::get('ads/restoreAll/{ids}','AdsController@restoreAll');
            //Tags Routes
            Route::resource('tags','TagsController')->except('show');
            Route::get('tags/delTag/{id}','TagsController@destroy');
            Route::get('tags/archiveAll/{ids}','TagsController@archiveAll');
            Route::get('tags/delAll/{ids}','TagsController@delAll');
            Route::get('tags_archive','TagsController@tags_archive');
            Route::get('tags/restoreAll/{ids}','TagsController@restoreAll');
            //Pages Routes
            Route::resource('pages','PagesController')->except('show');
            Route::get('pages/delPage/{id}','PagesController@destroy');
            Route::get('pages/archiveAll/{ids}','PagesController@archiveAll');
            Route::get('pages/delAll/{ids}','PagesController@delAll');
            Route::get('pages/changeStatus','PagesController@changeStatus');
            Route::get('pages_archive','PagesController@pages_archive');
            Route::get('pages/restoreAll/{ids}','PagesController@restoreAll');
            //Countries Routes
            Route::resource('countries','CountriesController')->except('show');
            Route::get('countries/delCountry/{id}','CountriesController@destroy');
            Route::get('countries/archiveAll/{ids}','CountriesController@archiveAll');
            Route::get('countries/delAll/{ids}','CountriesController@delAll');
            Route::get('countries_archive','CountriesController@countries_archive');
            Route::get('countries/restoreAll/{ids}','CountriesController@restoreAll');
            //Cities Routes
            Route::resource('cities','CitiesController');
            Route::get('cities/delCity/{id}','CitiesController@destroy');
            Route::get('cities/archiveAll/{ids}','CitiesController@archiveAll');
            Route::get('cities/delAll/{ids}','CitiesController@delAll');
            Route::get('cities_archive','CitiesController@cities_archive');
            Route::get('cities/restoreAll/{ids}','CitiesController@restoreAll');
            //Socials Routes
            Route::resource('socials','SocialsController')->except('show');
            Route::get('socials/delSocial/{id}','SocialsController@destroy');
            Route::get('socials/archiveAll/{ids}','SocialsController@archiveAll');
            Route::get('socials/delAll/{ids}','SocialsController@delAll');
            Route::get('socials_archive','SocialsController@socials_archive');
            Route::get('socials/restoreAll/{ids}','SocialsController@restoreAll');
            //Colors Routes
            Route::resource('colors','ColorsController')->except('show');
            Route::get('colors/delColor/{id}','ColorsController@destroy');
            Route::get('colors/archiveAll/{ids}','ColorsController@archiveAll');
            Route::get('colors/delAll/{ids}','ColorsController@delAll');
            Route::get('colors_archive','ColorsController@colors_archive');
            Route::get('colors/restoreAll/{ids}','ColorsController@restoreAll');
            //Sizes Routes
            Route::resource('sizes','SizesController')->except('show');
            Route::get('sizes/archiveSize/{id}','SizesController@archive');
            Route::get('sizes/delSize/{id}','SizesController@destroy');
            Route::get('sizes/archiveAll/{ids}','SizesController@archiveAll');
            Route::get('sizes/delAll/{ids}','SizesController@delAll');
            Route::get('sizes_archive','SizesController@sizes_archive');
            Route::get('sizes/restoreAll/{ids}','SizesController@restoreAll');
            //Categories Routes
            Route::resource('categories','CategoriesController')->except('show');
            Route::get('categories/archiveCategory/{id}','CategoriesController@archive');
            Route::get('categories/delCategory/{id}','CategoriesController@destroy');
            Route::get('categories_archive','CategoriesController@categories_archive');
            Route::get('categories/restoreAll/{ids}','CategoriesController@restoreAll');
            //Products Routes
            Route::resource('products','ProductsController')->except('show');
            Route::get('products/delProduct/{id}','ProductsController@destroy');
            Route::get('products/delAll/{ids}','ProductsController@delAll');
            Route::get('products/changeStatus','ProductsController@changeStatus');
            Route::post('products/media','ProductsController@storeMedia')->name('products.storeMedia');;
            Route::get('products/changeType','ProductsController@changeType');
            Route::get('products_archive','ProductsController@products_archive');
            Route::get('products/restoreAll/{ids}','ProductsController@restoreAll');
            Route::get('getUserProducts/{id}','ProductsController@getUserProducts');
            //delete image from server and remove it from dropzone box
            Route::get('products/deleteImag/{name}','ProductsController@del_image');
            //Users Routes
            Route::resource('users','UsersController')->except('show');
            Route::get('users/delUser/{id}','UsersController@destroy');
            Route::get('users/archiveAll/{ids}','UsersController@archiveAll');
            Route::get('users/delAll/{ids}','UsersController@delAll');
            Route::get('users/changeStatus','UsersController@changeStatus');
            Route::get('users/changeType','UsersController@changeType');
            Route::get('users_archive','UsersController@users_archive');
            Route::get('users/restoreAll/{ids}','UsersController@restoreAll');
            //Admins Routes
            Route::resource('admins','AdminsController')->except('show');
            Route::get('admins/archiveAll/{ids}','AdminsController@archiveAll');
            Route::get('admins/delAll/{ids}','AdminsController@delAll');
            Route::get('admins_archive','AdminsController@admins_archive');
            Route::get('admin/restoreAll/{ids}','AdminsController@restoreAll');
            
           //Alert Routes
            Route::get('alerts','AlertController@index');
            //ckeditor
            Route::post('ckeditor/upload', 'DashboardController@upload')->name('ckeditor.upload');
        });
    });

routes/web.php
<?php
Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function(){ 
        Route::group(['namespace'=> 'Site'],function(){
            Route::get('/','HomeController@index');
            //Login Route
            Route::post('postLogin','Auth\LoginController@postLogin')->name('postLogin');
            Route::post('userLogout','Auth\LoginController@userLogout')->name('userLogout');
            //Resigster Route
            Route::post('postSignup','Auth\RegisterController@newUser')->name('signup');
            //Socials Route
            Route::get('/auth/redirect/{provider}', 'Auth\SocialController@redirect');
            Route::get('/callback/{provider}', 'Auth\SocialController@callback');
            //User Routes
            Route::group(['middleware'=>'verified'],function(){
                Route::resource('user','UsersController')->except(['index','create','store','destroy']);
                //Route::get('profile/{id}','UserController@getProfile');
                Route::get('userProducts/{id}','UsersController@userProducts');
                Route::get('addProduct','UsersController@new_product');
                Route::get('myFavs/{id}','UsersController@myFavs');
                Route::get('myMsgs/{id}','UsersController@myMsgs');
                Route::resource('product','ProductsController')->except(['index']);
                Route::get('delProduct/{id}','ProductsController@destroy');
                //Products Dropzone media
                Route::post('product/media','ProductsController@storeMedia')->name('product.storeMedia');;
                Route::get('productImg/deleteImag/{name}','ProductsController@del_image');
            });
            Route::post('rateProduct','ProductsController@rateProduct')->name('product.rate');
            //categories routes
            Route::get('categories','CategoriesController@index')->name('categories');
            Route::get('category/{id}','CategoriesController@show')->name('categories.show');
            //products route
            Route::get('allProducts','HomeController@all_products');
            Route::get('showProduct/{slug}','ProductsController@show');
            //subscribe routes
            Route::post('subscribe','HomeController@subscribe')->name('subscribe');
            //Pages Route
            Route::get('getPage/{id}','HomeController@get_page')->name('getPage');
            //Route Contact Page
            Route::get('contact','HomeController@contact');
            Route::post('contactMsg','HomeController@contactMsg')->name('contactMessage');
            //Route To get All cities for one country
            Route::get('get_cities/{country_id}/{lang}','HomeController@get_cities');
            //Route to get all categories
            Route::get('all_categories','HomeController@all_cats');
            //ckeditor
            Route::post('ckeditor/upload', 'HomeController@upload')->name('ckeditor.uploadProduct');
            
        });
        Auth::routes(['verify'=> true]);
    });


Route::get('/home', 'Site\HomeController@index')->name('home');

app/Http/Controllers/Dashboard/AlertController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AlertController extends Controller
{
    public function __construct()
    {
        $this->middleware(['permission:read_alerts'])->only('index');      
        $this->middleware(['permission:delete_alerts'])->only(['destroy','delAll']);      
        $this->middleware(['permission:archive_alerts'])->only('archiveAll');      
    }
    public function index(){
        
    }
}

app/Http/Controllers/Dashboard/DashboardController.php
<?php

namespace App\Http\Controllers\Dashboard;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Setting;
use Intervention\Image\ImageManager;
use Intervention\Image\Facades\Image as Image;
use Illuminate\Validation\Rule;
use Illuminate\Support\Facades\Session;
use App\Models\Product;
use App\Models\Operation;
use Illuminate\Support\Facades\DB;
class DashboardController extends Controller
{
    public function index(){
        /*$products = Product::select(
            DB::raw('YEAR(created_at) as year'),
            DB::raw('MONTH(created_at) as month'),
        )->groupBy('month')->get(); */
        $products = Product::all();
        return view('dashboard.index',compact('products'));
    }
    public function noPermission(){
        toastr()->error(__('site.noPermissions'));
        return redirect('/cp');
    }
    public function operations(){
        if(auth()->user()->id == 1){
            $operations = Operation::orderBy('id','desc')->get();
            return view('dashboard.operation',compact('operations'));
        }else{
            toastr()->error(__('site.noPermissions'));
            return redirect('/cp');
        }
    }
    public function showAdminOperations($admin){
        if(auth()->user()->id == 1){
            $operations = Operation::orderBy('id','desc')->where('admin_id',$admin)->get();
            return view('dashboard.operation',compact('operations'));
        }else{
            toastr()->error(__('site.noPermissions'));
            return redirect('/cp');
        }
    }
    public function showOperations($section){
        if(auth()->user()->id == 1){
            $operations = Operation::orderBy('id','desc')->where('section',$section)->get();
            return view('dashboard.operation',compact('operations'));
        }else{
            toastr()->error(__('site.noPermissions'));
            return redirect('/cp');
        }
    }
    public function delOperation($ids){
        if(auth()->user()->id == 1){
            $operations_id = explode(',',$ids);
            foreach($operations_id as $op_id){
                $operation = Operation::where('id',$op_id)->delete();
                
            }
            if($operation){
                toastr()->success(__('site.deleted_successfully'));
                return redirect()->back();
            }
        }else{
            toastr()->error(__('site.noPermissions'));
            return redirect('/cp');
        }
    }
    // upload images via ckeditor
    public function upload(Request $request)
    {
        if($request->hasFile('upload')) {
            $originName = $request->file('upload')->getClientOriginalName();
            $fileName = pathinfo($originName, PATHINFO_FILENAME);
            $extension = $request->file('upload')->getClientOriginalExtension();
            $fileName = $fileName.'_'.time().'.'.$extension;
        
            $request->file('upload')->move(public_path('uploads/products'), $fileName);
   
            $CKEditorFuncNum = $request->input('CKEditorFuncNum');
            $url = asset('uploads/products/'.$fileName); 
            $msg = 'Image uploaded successfully'; 
            $response = "<script>window.parent.CKEDITOR.tools.callFunction($CKEditorFuncNum, '$url', '$msg')</script>";
               
            @header('Content-type: text/html; charset=utf-8'); 
            return $response;
        
        }
    }
}

app/Http/Controllers/Site/CategoriesController.php
<?php

namespace App\Http\Controllers\Site;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\Category;
use App\Models\Product;

class CategoriesController extends Controller
{
    public function index(){
        $cats = Category::where(['status'=>'1','parent_id'=> NULL])->orderBy('id','desc')->paginate(10);
        return view('site.categories',compact('cats'));
    }
    public function show($id){
        $category = Category::findOrFail($id);
        $cat = Category::with(['products', 'subproducts'])->where('id', $id)->first();
        $childs = $cat->products->merge($cat->subproducts);
        return view('site.category',compact('childs','category'));
    }
}

resources/views/dashboard/categories/create.blade.php
@extends('dashboard.layouts.app')
@section('content')
<div class="content-wrapper">

    <section class="content-header">

        <h1>@lang('site.categories')</h1>

        <ol class="breadcrumb">
        <li><a href="{{url('cp')}}"><i class="fa fa-dashboard"></i> @lang('site.dashboard')</a></li>
            <li class="active"><i class="fa fa-cog"></i>@lang('site.categories')</li>
        </ol>
    </section>

    <section class="content">

        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    
                <div class="box-body">
                    @if($errors->any())
                        @foreach ($errors->all() as $error)
                            <div class="alert alert-danger"><p class="text-center">{{$error}}</p></div>
                        @endforeach
					@endif  
                <form id="file-upload-form" class="uploader" action="{{route('categories.store')}}" method="post" enctype="multipart/form-data">
                    @csrf
                        @foreach (config('translatable.locales') as $locale)
                            <div class="form-group col-md-12">
                                <label>@lang('site.' . $locale . '.title')</label>
                                <input type="text" name="{{ $locale }}[title]" class="form-control" value="{{ old($locale . '.title') }}">
                            </div>
                            
                            <div class="form-group col-md-12">
                                <label>@lang('site.' . $locale .'.description')</label>
                                <textarea class="form-control" name="{{ $locale }}[description]" rows="3"></textarea>
                            </div>
                            <div class="form-group col-md-12">
                                <label>@lang('site.' . $locale .'.tags')</label>
                                <textarea class="form-control" name="{{ $locale }}[tags]" rows="3"></textarea>
                            </div>
                        @endforeach
                        <div class="form-group col-md-12">
                            <label>@lang('site.category')</label>
                            <div id="jstree"></div>
                            <input type="hidden" class="parent_id" value="{{old('parent_id')}}" name="parent_id">
                        </div>
                        <div class="form-group col-md-12">
                            <label>@lang('site.status')</label>
                            <select class="form-control" name="status">
                                <option value="0">@lang('site.not-active')</option>
                                <option value="1">@lang('site.active')</option>
                            </select>
                        </div>
                        <div class="form-group col-md-12">
                            <label>@lang('site.icon')</label>
                            <input type="file" id="logo_image" name="icon" class="form-control"/>
                            <br>
                            <img src="#" id="logo-img-tag" class="img-responsive img-thumbnail" />
                        
                        </div>
                        <div class="form-group col-md-12">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-plus"></i> @lang('site.add')</button>
                        </div>

                </form>

                </div>
            </div>
            </div>
        </div><!-- end of row -->

        
    </section><!-- end of content -->

</div><!-- end of content wrapper -->
  
@endsection
@push('scripts')
<script>
    //jstree categories
    $(document).ready(function(){
            $('#jstree').jstree({
                "core" : {
                    'data' : {!! load_cats(old('parent_id')) !!},
                    "themes" : {
                        "variant" : "large"
                    }
                },
                "checkbox" : {
                    "keep_selected_style" : false
                },
                "plugins" : [ "wholerow" ]
                });
    });
            $('#jstree').on('changed.jstree',function (e,data) {
                var i , j ,r = [];
                for(i=0,j = data.selected.length;i < j;i++){
                    r.push(data.instance.get_node(data.selected[i]).id);
                }
                $('.parent_id').val(r.join(', '));
            });
        </script>
   
@endpush

resources/views/dashboard/categories/edit.blade.php
@extends('dashboard.layouts.app')
@section('content')
<div class="content-wrapper">

    <section class="content-header">

        <h1>@lang('site.categories')</h1>

        <ol class="breadcrumb">
        <li><a href="{{url('cp')}}"><i class="fa fa-dashboard"></i> @lang('site.dashboard')</a></li>
            <li class="active"><i class="fa fa-cog"></i>@lang('site.categories')</li>
        </ol>
    </section>

    <section class="content">

        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    
                <div class="box-body">
                    @if($errors->any())
                        @foreach ($errors->all() as $error)
                            <div class="alert alert-danger"><p class="text-center">{{$error}}</p></div>
                        @endforeach
					@endif  
                <form id="file-upload-form" class="uploader" action="{{route('categories.update',$category->id)}}" method="post" enctype="multipart/form-data">
                    @csrf
                    @method('put')
                        @foreach (config('translatable.locales') as $locale)
                            <div class="form-group col-md-12">
                                <label>@lang('site.' . $locale . '.title')</label>
                                <input type="text" name="{{ $locale }}[title]" class="form-control" value="{{ $category->translate($locale)->title }}">
                            </div>
                            
                            <div class="form-group col-md-12">
                                <label>@lang('site.' . $locale .'.description')</label>
                            <textarea class="form-control" name="{{ $locale }}[description]">{{$category->translate($locale)->description }}</textarea>
                            </div>
                            <div class="form-group col-md-12">
                                <label>@lang('site.' . $locale .'.tags')</label>
                            <textarea class="form-control" name="{{ $locale }}[tags]">{{$category->translate($locale)->tags }}</textarea>
                            </div>
                        @endforeach
                        <div class="form-group col-md-12">
                            <label>@lang('site.category')</label>
                            <div id="jstree"></div>
                            <input type="hidden" class="parent_id" value="{{$category->parent_id}}" name="parent_id">
                        </div>
                        <div class="form-group col-md-12">
                            <label>@lang('site.status')</label>
                            <select class="form-control" name="status">
                                <option value="0" {{($category->status == '0') ? 'selected':''}}>@lang('site.not-active')</option>
                                <option value="1" {{($category->status == '1') ? 'selected':''}}>@lang('site.active')</option>
                            </select>
                        </div>
                        <div class="form-group col-md-12">
                            <label>@lang('site.icon')</label>
                            <input type="file" id="logo_image" name="icon" class="form-control"/>
                            <br>
                        <img src="{{url('uploads/categories/'.$category->icon)}}" id="logo-img-tag" class="img-responsive img-thumbnail" />
                        
                        </div>
                        <div class="form-group col-md-12">
                            <button type="submit" class="btn btn-primary"><i class="fa fa-pencil"></i> @lang('site.update')</button>
                        </div>

                </form>

                </div>
            </div>
            </div>
        </div><!-- end of row -->

        
    </section><!-- end of content -->

</div><!-- end of content wrapper -->
  
@endsection
@push('scripts')
<script>
    //jstree categories
    $(document).ready(function(){
            $('#jstree').jstree({
                "core" : {
                    'data' : {!! load_cats($category->parent_id,$category->id) !!},
                    "themes" : {
                        "variant" : "large"
                    }
                },
                "checkbox" : {
                    "keep_selected_style" : false
                },
                "plugins" : [ "wholerow" ]
                });
            });
            $('#jstree').on('changed.jstree',function (e,data) {
                var i , j ,r = [];
                for(i=0,j = data.selected.length;i < j;i++){
                    r.push(data.instance.get_node(data.selected[i]).id);
                }
                $('.parent_id').val(r.join(', '));
            });
        </script>
   
@endpush

resources/views/dashboard/categories/index.blade.php
@extends('dashboard.layouts.app')
@section('content')

<div class="content-wrapper">

    <section class="content-header">

        <h1>@lang('site.categories')</h1>

        <ol class="breadcrumb">
        <li><a href="{{url('cp')}}"><i class="fa fa-dashboard"></i> @lang('site.dashboard')</a></li>
            <li class="active"><i class="fa fa-cog"></i>@lang('site.categories')</li>
        </ol>
    </section>

    <section class="content">

        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                
                <div class="box-body">
                    @if($errors->any())
                        @foreach ($errors->all() as $error)
                            <div class="alert alert-danger"><p class="text-center">{{$error}}</p></div>
                        @endforeach
                    @endif  
                    <a href="{{route('categories.create')}}" class="btn btn-success"><i class="fa fa-plus"></i> @lang('site.create')</a>
                    <a href="" class="btn btn-info edit_dep showbtn_control hidden" ><i class="fa fa-edit"></i></a>
                    <a href="" class="btn btn-primary showbtn_control archive_confirm hidden"><i class="fa fa-archive"></i></a>
                    <a href="" class="btn btn-danger showbtn_control hidden delete-confirm"><i class="fa fa-trash"></i></a>
                    <br/>
                    <div id="jstree"></div>
                    <input type="hidden" class="parent_id" value="" name="parent_id">
                </div>
            </div>
            </div>
        </div><!-- end of row -->

        
    </section><!-- end of content -->

</div><!-- end of content wrapper -->
  
@endsection
@push('scripts')
        <script type="text/javascript">
            $(document).ready(function(){
                $('#jstree').jstree({
                    "core" : {
                        'data' : {!! load_cats(old('parent_id')) !!},
                        "themes" : {
                            "variant" : "large"
                        }
                    },
                    "checkbox" : {
                        "keep_selected_style" : true
                    },
                    "plugins" : [ "wholerow" ]
                });
            });
            $('#jstree').on('changed.jstree',function (e,data) {
                var i , j ,r = [];
                var name = [];
                for(i=0,j = data.selected.length;i < j;i++){
                    r.push(data.instance.get_node(data.selected[i]).id);
                    name.push(data.instance.get_node(data.selected[i]).text);
                }
                $("#form_Delete_department").attr('action','{{cp_url('categories')}}/'+r.join(', '));
                $("#dep_name").text(name.join(', '));
                $('.parent_id').val(r.join(', '));
                if(r.join(', ') != ''){
                    $('.showbtn_control').removeClass('hidden');
                    $('.edit_dep').attr('href','{{cp_url('categories')}}/'+r.join(', ')+'/edit');
                }
            });
            //confirm archive
            $('.archive_confirm').on('click',function (event) {
                event.preventDefault();
                 var cat_id = $('.parent_id').val()
                 const url = '{{url('cp/categories/archiveCategory')}}/'+cat_id;
                 swal({
                     title: '@lang('site.confirm_archive')',
                     text: '@lang('site.archive_msg')',
                     icon: 'warning',
                     buttons: ["@lang('site.no')", "@lang('site.yes')"],
                 }).then(function(value) {
                     if (value) {
                         window.location.href = url;
                     }
                     
                 });
             });
            // confirm delete
             $('.delete-confirm').on('click',function (event) {
                event.preventDefault();
                 var cat_id = $('.parent_id').val()
                 const url = '{{url('cp/categories/delCategory')}}/'+cat_id;
                 swal({
                     title: '@lang('site.confirm_delete')',
                     text: '@lang('site.delete_msg')',
                     icon: 'warning',
                     buttons: ["@lang('site.no')", "@lang('site.yes')"],
                 }).then(function(value) {
                     if (value) {
                         window.location.href = url;
                     }
                     
                 });
             });
             
         </script>
    @endpush